# Generated by Django 5.0.4 on 2024-04-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aadhar_student_stu_aadhar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('EXE', 'EXE'), ('IT', 'IT'), ('ME', 'ME'), ('MI/ML', 'MI/ML')], max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=200, verbose_name='Desc')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_aadhar',
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100, verbose_name='Name')),
                ('stu_class', models.CharField(choices=[('1', 'B.tech'), ('2', 'M.tech'), ('3', 'B.Com'), ('4', 'M.Com'), ('5', 'BCA'), ('6', 'MCA')], max_length=100, verbose_name='Class')),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_mobile', models.IntegerField()),
                ('stu_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.departmentmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Aadhar',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
