# Generated by Django 5.0.4 on 2024-04-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_departmentmodel_remove_student_stu_aadhar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='stu_department',
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(choices=[('Tata', 'Tata'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Nissan', 'Nissan'), ('Mitsubishi', 'Mitsubishi'), ('Subaru', 'Subaru'), ('Mazda', 'Mazda'), ('Mitsubishi', 'Mitsubishi')], max_length=255)),
                ('fuel_name', models.ManyToManyField(to='app.fueltypemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='DepartmentModel',
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
